export enum ParentActions {
  FETCH_STUDENTS = 'PARENT/FETCH_STUDENTS',
  FETCH_STUDENTS_FAILURE = 'PARENT/FETCH_STUDENTS_FAILURE',
  FETCH_STUDENTS_SUCCESS = 'PARENT/FETCH_STUDENTS_SUCCESS',
  ADD_STUDENT = 'PARENT/ADD_STUDENT',
  ADD_STUDENT_SUCCESS = 'PARENT/ADD_STUDENT_SUCCESS',
  ADD_STUDENT_FAILURE = 'PARENT/ADD_STUDENT_FAILURE',
  EDIT_STUDENT = 'PARENT/EDIT_STUDENT',
  EDIT_STUDENT_SUCCESS = 'PARENT/EDIT_STUDENT_SUCCESS',
  EDIT_STUDENT_FAILURE = 'PARENT/EDIT_STUDENT_FAILURE',
  DELETE_STUDENT = 'PARENT/DELETE_STUDENT',
  DELETE_STUDENT_SUCCESS = 'PARENT/DELETE_STUDENT_SUCCESS',
  DELETE_STUDENT_FAILURE = 'PARENT/DELETE_STUDENT_FAILURE',
}
