export enum RequestActions {
  FETCH_REQUEST = 'REQUEST/FETCH_REQUEST',
  FETCH_REQUEST_SUCCESS = 'REQUEST/FETCH_REQUEST_SUCCESS',
  FETCH_REQUEST_FAILURE = 'REQUEST/FETCH_REQUEST_FAILURE',
  FETCH_REQUESTS = 'REQUEST/FETCH_REQUESTS',
  FETCH_REQUESTS_SUCCESS = 'REQUEST/FETCH_REQUESTS_SUCCESS',
  FETCH_REQUESTS_FAILURE = 'REQUEST/FETCH_REQUESTS_FAILURE',
  CREATE_REQUEST = 'REQUEST/CREATE_REQUESTS',
  CREATE_REQUEST_SUCCESS = 'REQUEST/CREATE_REQUESTS_SUCCESS',
  CREATE_REQUEST_FAILURE = 'REQUEST/CREATE_REQUESTS_FAILURE',
  EDIT_REQUEST = 'REQUEST/EDIT_REQUEST',
  EDIT_REQUEST_SUCCESS = 'REQUEST/EDIT_REQUEST_SUCCESS',
  EDIT_REQUEST_FAILURE = 'REQUEST/EDIT_REQUEST_FAILURE',
  DELETE_REQUEST = 'REQUEST/DELETE_REQUEST',
  DELETE_REQUEST_SUCCESS = 'REQUEST/DELETE_REQUEST_SUCCESS',
  DELETE_REQUEST_FAILURE = 'REQUEST/DELETE_REQUEST_FAILURE'
}
