export enum StudentActions {
    UPDATE_STUDENT_DETAILS = 'STUDENT/UPDATE_STUDENT_DETAILS',
    UPDATE_STUDENT_DETAILS_SUCCESS = 'STUDENT/UPDATE_STUDENT_DETAILS_SUCCESS',
    UPDATE_STUDENT_DETAILS_FAILURE = 'STUDENT/UPDATE_STUDENT_DETAILS_FAILURE',
    FETCH_STUDENT_DETAILS = 'STUDENT/FETCH_STUDENT_DETAILS',
    FETCH_STUDENT_DETAILS_SUCCESS = 'STUDENT/FETCH_STUDENT_DETAILS_SUCCESS',
    FETCH_STUDENT_DETAILS_FAILURE = 'STUDENT/FETCH_STUDENT_DETAILS_FAILURE',
}
