export enum TimezonesActions {
  FETCH_TIMEZONES = 'TIMEZONES/FETCH_TIMEZONES',
  FETCH_TIMEZONES_SUCCESS = 'TIMEZONES/FETCH_TIMEZONES_SUCCESS',
  FETCH_TIMEZONES_FAILURE = 'TIMEZONES/FETCH_TIMEZONES_FAILURE',
}
