export enum Routes {
    HomePage = '/',
    Registration = '/registration',
    RegistrationStudent = '/registration-student',
    RegistrationParent = '/registration-parent',
    RegistrationInstructor = '/registration-instructor',
    Requests = '/requests',
    BuildProfile = '/build-profile',
    BuildRequest = '/build-request',
    BuildRequestStep = '/build-request/:step',
    BuildProfileStep = '/build-profile/:step',
    Request = '/request',
    RequestId = '/request/:id',
    Login = '/login',
    Profile = '/profile/:instructorId',
    AccountRecovery = '/account-recovery',
    ForgotPassword = '/forgot-password',
    TermsOfUse = '/terms-of-use',
    PrivacyPolicy = '/privacy-policy',
    InstructorPolicy = '/instructor-policy',
    StudentPolicy = '/student-policy',
    ContactUs = '/contact-us',
    AccountInfo = '/account-info',
    Dashboard = '/dashboard',
    Applications = '/applications',
    Messages = '/messages',
    Lessons = '/lessons',
    JobRequests = '/job-requests',
    Payments = '/payments',
    Settings = '/settings',
    MyInstructors = '/my-instructors',
    Help = '/help',
    Instructors = '/instructors',
    BookLessons = '/book-lessons',
    Pricing = '/pricing',
    WelcomeMessage = '/welcome-message'
}

export enum SocialLinks {
    Facebook = 'https://www.facebook.com/nabimusicinfo',
    Twitter = 'https://twitter.com/_nabimusic',
    Instagram = 'https://www.instagram.com/_nabimusic',
    Pinterest = 'https://www.pinterest.com/nabimusic_/'
}
