import * as React from 'react';
import Link from 'next/link';
import Head from 'next/head';

import { Routes } from '../constants/Routes';
import { pageTitlesAndDescriptions } from '../constants/TitlesAndDescriptions';

import { Typography } from '@material-ui/core';

export const TermsOfUse: React.StatelessComponent<{}> = props => {
  // tslint:disable
  return (
    <div className="nabi-container">
      <Head>
        <title>{pageTitlesAndDescriptions.termsOfUse.title}</title>
        <meta name="description" content={pageTitlesAndDescriptions.termsOfUse.description}></meta>
      </Head>
      <Typography variant="h3" align="center">Terms of Use</Typography>
      <Typography variant="h3" align="center">Last modified: Oct 15, 2019</Typography>

      Welcome to NabiMusic.com (the “Website”), an online marketplace operated by Nabi Music Center, LLC. (hereafter “us” “we” “our” “NabiMusic” “Nabi Music” or “Nabi”) connecting students (“Students”) with a network of independent contractor instruction providers (hereafter “Instructors” or “Instructor Members”). This Terms of Use (the “Agreement”) binds you or the entity you represent (“you” or “your”) to the terms and conditions set forth herein when you use or access the Website or any of our software, applications, sites, materials, products, tools and other offerings (collectively, the “Services”). If you wish to use our Services, you must read, comply with and agree to be bound by the terms of this Agreement. If you object to anything in this Agreement, do not use our Services.

      <Typography variant="h2">1. Acceptance of Terms of Use Agreement</Typography>
      This Agreement is an electronic contract that sets out the legally binding terms of your use of our Services, whether or not you register as a “Student Member” or “Instructor Member” (each may be referred to as a “Member”). This Agreement includes our <Link href={Routes.PrivacyPolicy}>Privacy Policy</Link>, Student and Instructor Policies, our billing policies and any further terms of use for our Services, which are all incorporated herein by reference. This Agreement may be modified by us from time to time, such modifications to be effective when provided in writing or upon posting within our Services. Certain parts of our Services may have different terms and conditions posted or may require you to agree with and accept additional terms and conditions. If there is a conflict between this Agreement and terms and conditions posted for a specific area of or within our Services, the latter terms and conditions will take precedence with respect to your use of or access to that specific Service, but this Agreement shall still apply to our legal relationship. You have the right to receive this Agreement in non-electronic form, either before or after you electronically sign the Agreement, by sending a written request and self-addressed stamped envelope to: Nabi Music, 1609 Clinton Ave, South Plainfield, New Jersey 08070.
      <Typography variant="h2">2. Eligibility</Typography>
      Membership in or use of our Services is void where prohibited. Any access to or use of our Services by anyone under the age of majority is expressly prohibited and requires consent to this Agreement by a parent or legal guardian. By using our Services, you represent and warrant to us that you are either a legal adult or, if under the age of majority, have obtained proper consent from a parent or legal guardian. If you use our Services on behalf of a company or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to this Agreement. By using our Services, you represent and warrant that you have the right, authority and capacity to enter into this Agreement and to abide by all of the terms and conditions of this Agreement.
      <Typography variant="h2">3. How the Service Works</Typography>
      We are an online marketplace for Students and a network of independent contractor music Instructors. We do not endorse, hire or employ the Instructor Members nor are we responsible or liable for any interactions involved between Instructor Members and their respective Student Members or between Members. Instructor Members and Student Members are solely responsible for all interactions, conversations, and any form of communication and behavior between any other Member. Our Services are separate and distinct from the services of Instructor Members.
      <br />
      <br />
      For Instructor Members, we offer various hosted products to support instruction including marketing, scheduling, billing and communication tools. Instructor Members can also apply to use our Services where prospective Students can review their profile, communicate with Instructor Members and book and pay for music lessons and other services ancillary thereto (called a "Profile").
      <br />
      <br />
      For Student Members, we provide a marketplace to find a network of independent contractor Instructor Members and schedule music lessons and other services ancillary thereto. We also provide a platform for group music lessons and online music lessons. Users may be able to request an instructor by posting a listing called “Request”. Users may be able to review Profiles as an unregistered user of our Services; however, if you wish to book a music lesson as a Student, to create a Profile as an Instructor, to use hosted tools or use certain Services, you must first become a registered Member. See the “How It Works” section of the Website for more information.
      <br />
      <br />
      If a particular Instructor, product or Service is discontinued or unavailable, we reserve the right to provide substitute Instructor, product or Service.
      <Typography variant="h2">4. Membership</Typography>
      You may use some of our Services at no direct cost. However, in order to access additional features and Services, including the ability to book or manage lessons, you must become a registered Member. To become a Member, you agree to provide accurate, current and complete information during the registration process and to update such information to keep it accurate, current and complete throughout your use of the Services. A Member may not have more than one active Nabi Music Account. We reserve the right to suspend or terminate your Nabi Music Account and your access to our Services for any reason.
      <h5>a. Student Membership.</h5>
      You must be at least eighteen (18) years old to be a Student Member. As a Student Member, you will have the ability to book and pay for lessons, manage your lesson schedule, communicate with Instructors, access help documents and use any other Services provided to Student Members. In addition, you will have the opportunity to apply for a Request. Acceptance for Requests is at our sole discretion and we may remove Requests from our Services at any time for any reason. Any Request you post (i) must not breach any agreements you have entered into with anyone, including this Agreement; and (ii) must contain accurate, current and complete information. As a Student Member you must continually comply with this Agreement and the Student Policies set forth <Link href={Routes.StudentPolicy}>here</Link>. Additional terms and conditions of service may be contained within your Student Member account.
      <h5>b. Provider Membership.</h5>
      You must be at least eighteen (18) years old to be an Instructor Member. As an Instructor Member, you will have access to tools that enable you to manage marketing, scheduling, billing and communication and other tools provided by us. In addition, you will have the opportunity to apply for a Profile. Acceptance for Profiles is at our sole discretion and we may remove Profiles from our Services at any time for any reason. Any Profile you post (i) must not breach any agreements you have entered into with anyone, including this Agreement; and (ii) must contain accurate, current and complete information. If you are accepted and your Profile is presented within our Services, you must continually comply with this Agreement and the <Link href={Routes.InstructorPolicy}>Instructor Policies</Link> set forth here. Any Instructor Member who accepts a booking through our Services must honor all terms and conditions of the Profile, this Agreement and any our additional Instructor Policies in effect at the time of booking. As part of your Instructor Membership, you will be required to receive messages via text / SMS and may incur costs from your carrier or mobile service provider as a result of these messages. Additional terms and conditions of service may be contained within your Instructor Member account.
      <h5>c. Independent Contractor Status.</h5>
      Our Services are separate and distinct from the services of the Instructors. You acknowledge that Instructor Members are not employees or agents of Nabi Music but are independent contractors who operate a separate and distinct business from Nabi Music. As such, we do not endorse or control the Instructors, the manner or method of service to you, exercise no control over your working relationship with the Instructor Member and do not warrant your safety or the service of any Instructor Member. We urge all users of our Services to be responsible and careful about their use of our Services, any transaction entered into as a result of our Services and interactions with Instructors.
      <h5>d. General Disclaimer.</h5>
      We disclaim all, and assume no responsibility for, evaluating or verifying the accuracy, suitability, truthfulness or authenticity of any information contained within the Profiles or Requests or of any information posted or provided by a Member. We assume no responsibility for ensuring a Member’s compliance with any applicable laws, rules and regulations or this Agreement. We have not inspected the location where any instruction will be provided. We are not responsible for the conduct, whether online or offline, of any user of our Services. Under no circumstances will we or any of our employees, officers, agents, advertisers or affiliates be responsible for any loss or damage, including personal injury or death, resulting from anyone's use of the Website or our Services, any content posted on the Website or transmitted to Members, or any interactions between users of our Services, whether online or offline. We cannot guarantee and do not promise any specific results from use of our Services.
      <br />
      <br />
      Some of our Services may require Students to have a computer and a sustained and reliable internet connection. We do not provide refunds for technical failures, power outages or unreliable internet connections beyond our control.
      <br />
      <br />
      Our Services may give you access to links to third-party websites ("Third Party Sites"), either directly or through Instructors. We do not endorse any of these Third Party Sites and do not control them in any manner. Accordingly, we do not assume any liability associated with Third Party Sites. You need to take appropriate steps to determine whether accessing a Third Party Site is appropriate, and to protect your personal information and privacy on such Third Party Site.
      <br />
      <br />
      We cannot guarantee that each Member is at least the required minimum age, nor do we accept responsibility or liability for any content, communication or other use or access of our Services by persons under the age of majority in violation of this Agreement. Also, it is possible that other Members or users (including unauthorized users, or "hackers") may post or transmit offensive or obscene materials using our Services and that you may be involuntarily exposed to such offensive and obscene materials. It also is remotely possible for others to obtain personal information about you due to your use of our Services, and that the recipient may use such information to harass or injure you. We are not responsible for the use of any personal information that you disclose using our Services. Please carefully select the type of information that you post on the Website or release to others using our Services. WE DISCLAIM ALL LIABILITY, REGARDLESS OF THE FORM OF ACTION, FOR THE ACTS OR OMISSIONS OF OTHER MEMBERS OR USERS (INCLUDING UNAUTHORIZED USERS), WHETHER SUCH ACTS OR OMISSIONS OCCUR DURING THE USE OF THE WEBSITE, OUR SERVICES OR OTHERWISE.
      <h5>e. Warranty Disclaimer.</h5>
      OUR WEBSITE, CONTENT, SUBMITTED CONTENT, COURSES, AND ANY OTHER MATERIALS MADE AVAILABLE ON OR THROUGH THE USE OF OUR SERVICES ARE PROVIDED "AS IS," WITHOUT ANY WARRANTIES OF ANY KIND AND, TO THE FULLEST EXTENT PERMISSIBLE UNDER APPLICABLE LAW, WE HEREBY DISCLAIM ALL SUCH WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, BUT NOT LIMITED TO, WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, ACCURACY, FREEDOM FROM ERRORS, SUITABILITY OF CONTENT, OR AVAILABILITY.
      <h5>f. Code of Conduct.</h5>
      While using our Services you agree not to:
      <ul>
        <li>Restrict or inhibit any other visitor or Member from using our Services, including, without limitation, by means of "hacking" or "cracking" or defacing any portion of our Services;</li>
        <br />
        <li>Use our Services for any unlawful purpose;</li>
        <br />
        <li>Express or imply that any statements you make are endorsed by us, without our prior written consent;</li>
        <br />
        <li>Transmit (a) any content, language, imagery, or information that is unlawful, fraudulent, threatening, harassing, abusive, libelous, defamatory, obscene or otherwise objectionable, or infringes on our or any third party's intellectual property or other rights; (b) any material, non-public information about companies without the authorization to do so; (c) any trade secret of any third party; or (d) any advertisements, solicitations, chain letters, pyramid schemes, investment opportunities, or other unsolicited commercial communication (except as otherwise expressly permitted by us);</li>
        <br />
        <li>Engage in spamming or flooding;</li>
        <br />
        <li>Breach or circumvent any laws, third-party rights or our systems, policies, or determinations of your account status;</li>
        <br />
        <li>Transmit any software or other materials that contain any virus, worm, time bomb, Trojan horse, or other harmful or disruptive component;</li>
        <br />
        <li>Modify, adapt, sublicense, translate, sell, reverse engineer, decompile or disassemble any portion of the Website or our Services;</li>
        <br />
        <li>Remove any copyright, trademark, or other proprietary rights notices contained on the Website or applied to our Services;</li>
        <br />
        <li>"Frame" or "mirror" any part of the Website or our Services without our prior written authorization;</li>
        <br />
        <li>Use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, "data mine," or in any way reproduce or circumvent the navigational structure or presentation of the Website or its contents;</li>
        <br />
        <li>Harvest or collect information about Website visitors or Members without their express consent;</li>
        <br />
        <li>Create more than one profile without our express written consent;</li>
        <br />
        <li>Permit anyone else whose account or subscription was terminated, or who is not a Member, to use our Services through your subscription, username or password;</li>
        <br />
        <li>Engage in commercial activities and/or sales without our prior written consent such as contests, sweepstakes, barter, advertising, and pyramid schemes;</li>
        <br />
        <li>Transfer your account or user ID to another party without our consent;</li>
        <br />
        <li>Be disruptive in any lesson or group instruction;</li>
        <br />
        <li>Solicit any instructor or user to work with or for another company for employment, independent contracting services, performances, or other service; or Engage in any communication related to sexual conduct, nudity, or which expresses profanity.</li>
      </ul>
      <Typography variant="h2">5. Pricing.</Typography>
      We provide three lesson packages, The Artist which includes 4 lessons, The Maestro which includes 8 lessons and The Virtuoso which includes 12 lessons. Users also have the option to buy a single lesson. Each package includes a Free Trial. Lesson prices are agreed to at the time of payment for the number of lessons purchased. Lesson prices vary by Instructor and lesson type and are subject to change at any time. Student Members and Instructor Members are obligated to honor the prices established at the time of payment. See additional Student and Instructor Policies set forth <Link href={Routes.StudentPolicy}>here</Link> and <Link href={Routes.InstructorPolicy}>here</Link>. Additional pricing terms and conditions are contained within Member and Instructor accounts and within email correspondence from Nabi Music. Refunds are not provided for acts taken in violation of this Agreement or for technical failures, power outages or unreliable internet connections beyond our control.
      <Typography variant="h2">6. Free Trial.</Typography>
      For Student Members, when a Student Member purchases one of our packages (The Artist, The Maestro or The Virtuoso) an additional lesson is included. If the Student Member is not satisfied with the Service, the Student Member must contact us to cancel the services and receive a full refund. If the Student Member is satisfied with the Service, the Student Member may continue to consume the lesson package the Student Member purchased.
      <br />
      For Instructor Members, when a Student Member purchases one of our packages (The Artist, The Maestro or The Virtuoso) an additional lesson is included.  If the Student Member is not satisfied with the Service after the Free Trial, the Instructor Member does not receive any compensation for the Free Trial.  If the Student Member is satisfied with the Service, the Instructor Member receives compensation for the Free Trial
      <Typography variant="h2">7. Term</Typography>
      This Agreement will remain in full force and effect while you use our Services and/or are a Member. You may terminate your membership at any time, for any reason, by sending written notice of termination to Nabi Music, 1609 Clinton Avenue, South Plainfield, New Jersey 07080. To help us analyze and improve our Services, you may be asked to provide a reason for your resignation/cancellation. We may terminate your membership and/or subscription at any time through notice to your email address on file. If we terminate your membership because you have breached this Agreement, you will not be entitled to any refund of unused subscription fees. All decisions regarding the termination of accounts shall be made in our sole discretion. We are not required to provide you notice prior to terminating your membership. We are not required, and may be prohibited, from disclosing a reason for the termination of your account. After your membership or subscription is terminated, all terms that by their nature may survive termination of this Agreement shall be deemed to survive such termination.
      <Typography variant="h2">8. Non-Circumvention</Typography>
      During the term of this Agreement and for two years thereafter, no Member shall, directly or indirectly, circumvent, initiate, solicit, negotiate, contract or enter into any business transactions with any Member introduced by us through our Services, without our consent. In case of such circumvention, such Member agrees and guarantees that such Member will pay a legal monetary penalty that is equal to the commission or fee we would have realized in such transactions, had Member not circumvented our rights under this Agreement.
      <Typography variant="h2">9. No Non-Permitted Use by Members</Typography>
      Use of our Services is only with our permission, which may be revoked at any time, for any reason, in our sole discretion. Illegal and/or unauthorized uses of our Services may be referred for criminal prosecution.
      <Typography variant="h2">10. Account Security</Typography>
      You are responsible for maintaining the confidentiality of your username and password. You shall not disclose your password to any unauthorized third party and will take sole responsibility for any activities or actions under your Nabi Music Account, whether or not you have authorized such activities or actions. You agree to (a) immediately notify us of any unauthorized use of your username or password or any other breach of security, and (b) ensure that you exit from your account at the end of each session. We will not be liable for any loss or damage arising from your failure to comply with this provision. You should use particular caution when accessing your account from a public or shared computer so that others are not able to view or record your password or other personal information. If you share your computer with others, you may wish to consider disabling any auto-sign in features if linked to your Nabi Music account.
      <Typography variant="h2">11. Your Interactions with Other Members and Our Limitation of Liability</Typography>
      <ul>
        <li>a. YOU ARE SOLELY RESPONSIBLE FOR YOUR INTERACTIONS WITH OTHER MEMBERS. YOU UNDERSTAND THAT NOT ALL PROVIDERS ON THE WEBSITE HAVE BACKGROUND CHECKS AND THAT WE DO NOT PERFORM BACKGROUND CHECKS ON STUDENT MEMBERS. THE EXTENT OF OUR BACKGROUND CHECK IS LIMITED BY THE QUALITY AND SCOPE OF SERVICE PROVIDED BY OUR THIRD PARTY INVESTIGATIVE SERVICE AND THE LIMITATIONS OF COMPUTER ACCESSIBLE PUBLIC RECORDS. NOT ALL JURISDICTIONS OR CRIMES ARE EVALUATED AS PART OF THE CRIMINAL BACKGROUND CHECK. WE DO NOT ATTEMPT TO VERIFY THE QUALIFICATION OR STATEMENTS OF OUR MEMBERS. WE MAKE NO REPRESENTATIONS OR WARRANTIES AS TO THE CONDUCT OF MEMBERS OR THEIR COMPATIBILITY WITH ANY CURRENT OR FUTURE MEMBERS.</li>
        <br />
        <li>b. NO MEMBER IS OBLIGATED TO MEET OFFLINE WITH ANY OTHER MEMBER. YOU AGREE TO TAKE REASONABLE PRECAUTIONS IN ALL INTERACTIONS WITH OTHER MEMBERS OF OUR SERVICES. YOU UNDERSTAND THAT WE MAKE NO GUARANTEES, EITHER EXPRESS OR IMPLIED, REGARDING YOUR ULTIMATE EXPERIENCE WITH MEMBERS YOU MEET THROUGH OUR SERVICES. YOU DO SO AT YOUR OWN RISK AND AT YOUR OWN PERIL.</li>
        <br />
        <li>c. IN NO EVENT SHALL NABI MUSIC  AND/OR ITS OFFICERS, EMPLOYEES, AGENTS OR AFFILIATES BE LIABLE TO YOU OR ANY THIRD PERSON FOR ANY DAMAGES WHATSOEVER, WHETHER DIRECT, INDIRECT, GENERAL, SPECIAL, COMPENSATORY, CONSEQUENTIAL, EXEMPLARY, AND/OR INCIDENTAL, INCLUDING LOST PROFITS, ARISING OUT OF OR RELATING TO ANY ACT OR OMISSIONS OF YOU, TAKE LESSONS AND/OR ITS OFFICERS, EMPLOYEES, AGENTS OR AFFILIATES, OUR THIRD PARTY INVESTIGATIVE SERVICE, ANY MEMBER OR ANYONE ELSE IN CONNECTION WITH THE USE OF OUR SERVICES OR THE WEBSITE, INCLUDING WITHOUT LIMITATION, BODILY INJURY, EMOTIONAL DISTRESS, AND/OR ANY OTHER DAMAGES RESULTING FROM COMMUNICATIONS OR MEETINGS WITH OTHER USERS OF OUR SERVICES OR PERSONS YOU MEET THROUGH OUR SERVICES, OR OTHERWISE.</li>
        <br />
        <li>d. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, AND TO THE MAXIMUM EXTENT ALLOWED BY LAW,THE LIABILITY OF TAKE LESSONS AND/OR ITS OFFICERS, EMPLOYEES, AGENTS AND AFFILIATES, TO YOU AND YOUR HEIRS AT LAW FOR ANY CAUSE WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, SHALL BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU TO US FOR OUR SERVICES DURING THE PRECEDNG TWELVE MONTHS, UP TO A MAXIMUM OF FIVE THOUSAND DOLLARS.</li>
      </ul>
      <Typography variant="h2">12. Content within our Services</Typography>
      <ul>
        <li>
          a. Proprietary Rights.
          The Website and our Services contains the copyrighted material, trademarks, and other proprietary information of Nabi Music, and its licensors. Except for that information which is in the public domain or for which you have been given written permission, you may not copy, modify, publish, transmit, distribute, perform, display, or sell any such proprietary information.
        </li>
        <br />
        <li>
          b. Reliance on Content, Advice, Etc.
          Opinions, advice, statements, reviews, offers, or other information or content made available through our Services, but not directly by us, are those of their respective authors, and should not necessarily be relied upon. Such authors are solely responsible for such content.
        </li>
      </ul>
      <Typography variant="h2">13. Content Posted by You</Typography>
      As a Member, you may be able to post Content (herein defined as uploading videos, photos, providing reviews of Members, attendance in live classes online through Nabi Music owned technology, and other forms of user contributions to the Site or Service). You are solely responsible for the Content that you publish or display (hereinafter, “post”) using our Services, or transmit or display to other Members. You will not post on the Website or Service, or transmit or display to other Members, any defamatory, inaccurate, false, abusive, obscene, profane, offensive, sexually oriented, threatening, harassing, racially offensive, or illegal material, or any material that infringes or violates another party's rights (including, but not limited to, intellectual property rights, and rights of privacy and publicity). By posting Content using our Services, including attending any online class through Nabi Music Live or any other part of the Nabi Music Service, you automatically grant, and you represent and warrant that you have the right to grant, to us, our affiliates, licensees and successors, an irrevocable, perpetual, non-exclusive, fully paid, worldwide license to use, copy, perform, display, record, reproduce, adapt, modify and distribute such information and content and to prepare derivative works of, or incorporate into other works, such information and content, and to grant and authorize sublicenses of the foregoing. You further represent and warrant that public posting and use of your content by us will not infringe or violate the rights of any third party.
      <Typography variant="h2">14. Customer Service</Typography>
      We may provide assistance and guidance through our customer care representatives. Telephone calls, and chat messages between you and our customer care representatives may be recorded or saved for quality assurance purposes. If we feel that your behavior towards any of our customer care representatives or other employees is at any time threatening or offensive, we reserve the right to immediately terminate your membership and you will not be entitled to any refund of unused subscription fees.
      <Typography variant="h2">15. Modification to Services</Typography>
      We reserve the right at any time to modify or discontinue, temporarily or permanently, our Services (or any part thereof) with or without notice. You agree that we shall not be liable to you or to any third party for any modification, suspension or discontinuance of our Services. Notification of changes to our Services may be posted within your Member profile, on the Website or communicated through our Services.
      <Typography variant="h2">16. Copyright Policy</Typography>
      The Digital Millennium Copyright Act of 1998 (the "DMCA") provides recourse for copyright owners who believe that material appearing on the Internet infringes their rights under U.S. Copyright law. You may not post, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior written consent of the owner of such proprietary rights. Without limiting the foregoing, if you believe that your work has been copied and posted on the Website or used in any of our Services in a way that constitutes copyright infringement, please contact us immediately at <a href="mailto:info@nabimusic.com">info@nabimusic.com</a>.
      <Typography variant="h2">17. Member Disputes</Typography>
      You are solely responsible for your interactions with other Members. We reserve the right, but not the obligation, to monitor disputes between you and other Members.
      <Typography variant="h2">18. Privacy and Communications</Typography>
      Use of our Services is also governed by our <Link href ={Routes.PrivacyPolicy}>Privacy Policy</Link>. When you become a Member, you agree and consent to receive email messages from us. These emails may be transactional or relationship communications relating to our Services, such as administrative notices and service announcements or changes, or emails containing commercial offers, promotions or special offers from us. Please see our <Link href ={Routes.PrivacyPolicy}>Privacy Policy</Link> for more information regarding these communications.
      <Typography variant="h2">19. Links</Typography>
      Our Services may provide, or third parties may provide, links to other websites or resources. Because we have no control over such sites and resources, you acknowledge and agree that we are not responsible for the availability of such external sites or resources, and do not endorse and are not responsible or liable for any content, advertising, products or other materials on or available from such sites or resources. You further acknowledge and agree that we shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of, or reliance upon, any such Content, goods or services available on or through any such site or resource.
      <Typography variant="h2">20. U.S. Export Controls</Typography>
      Software from this Website (the “Software”) is further subject to United States export controls. No Software may be downloaded from the Website or otherwise exported or re-exported (i) into (or to a national or resident of) Cuba, Iraq, Libya, North Korea, Iran, Syria, or any other Country to which the U.S. has embargoed goods; or (ii) to anyone on the U.S. Treasury Department's list of Specially Designated Nationals or the U.S. Commerce Department's Table of Deny Orders. By downloading or using the Software, you represent and warrant that you are not located in, under the control of, or a national or resident of any such country or on any such list.
      <Typography variant="h2">21. Arbitration and Governing Law</Typography>
      PLEASE READ THIS SECTION CAREFULLY. IT AFFECTS YOUR RIGHTS AND WILL HAVE A SUBSTANTIAL IMPACT ON HOW CLAIMS YOU AND NABI MUSIC HAVE AGAINST EACH OTHER ARE RESOLVED.
      <br />
      <br />
      You and Nabi Music agree that any claim or dispute at law or equity that has arisen or may arise between us relating in any way to or arising out of this or previous versions of the Terms of Use, your use of or access to our Services, or any products or services sold or purchased through our Services, will be resolved in accordance with the provisions set forth in this Section (“Agreement to Arbitrate”).
      <br />
      <ul>
        <li>
          a. Applicable Law
          <br />
          You agree that, except to the extent inconsistent with or preempted by federal law, the laws of the State of Massachusetts, without regard to principles of conflict of laws, will govern this Agreement and any claim or dispute that has arisen or may arise between you and Nabi Music, except as otherwise stated in this Agreement.
        </li>
        <br />
        <li>
          b. Agreement to Arbitrate
          <br />
        You and Nabi Music each agree that any and all disputes or claims that have arisen or may arise between you and Nabi Music relating in any way to or arising out of this or previous versions of the Terms of Use, your use of or access to Nabi Music's Services, or any products or services sold, offered, or purchased through Nabi Music shall be resolved exclusively through final and binding arbitration, rather than in court. Alternatively, you may assert your claims in small claims court, if your claims qualify and so long as the matter remains in such court and advances only on an individual (non-class, non-representative) basis. The Federal Arbitration Act governs the interpretation and enforcement of this Agreement to Arbitrate.
        </li>
        <br />
        <li>
          1. Prohibition of Class and Representative Actions and Non-Individualized Relief. YOU AND NABI MUSIC AGREE THAT EACH OF US MAY BRING CLAIMS AGAINST THE OTHER ONLY ON AN INDIVIDUAL BASIS AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE ACTION OR PROCEEDING. UNLESS BOTH YOU AND NABI MUSIC AGREE OTHERWISE, THE ARBITRATOR MAY NOT CONSOLIDATE OR JOIN MORE THAN ONE PERSON'S OR PARTY'S CLAIMS, AND MAY NOT OTHERWISE PRESIDE OVER ANY FORM OF A CONSOLIDATED, REPRESENTATIVE, OR CLASS PROCEEDING. ALSO, THE ARBITRATOR MAY AWARD RELIEF (INCLUDING MONETARY, INJUNCTIVE, AND DECLARATORY RELIEF) ONLY IN FAVOR OF THE INDIVIDUAL PARTY SEEKING RELIEF AND ONLY TO THE EXTENT NECESSARY TO PROVIDE RELIEF NECESSITATED BY THAT PARTY'S INDIVIDUAL CLAIM(S). ANY RELIEF AWARDED CANNOT AFFECT OTHER USERS.
          <br />
          <br />
          2. Arbitration Procedures. Arbitration is more informal than a lawsuit in court. Arbitration uses a neutral arbitrator instead of a judge or jury, and court review of an arbitration award is very limited. However, an arbitrator can award the same damages and relief on an individual basis that a court can award to an individual. An arbitrator should apply the terms of this Agreement as a court would. All issues are for the arbitrator to decide, except as prohibited by law.
          <br />
          The arbitration will be conducted by the American Arbitration Association ("AAA") under its rules and procedures, including the AAA's Consumer Arbitration Rules (as applicable), as modified by this Agreement to Arbitrate. The AAA's rules are available at www.adr.org or by calling the AAA at 1-800-778-7879. The use of the word "arbitrator" in this provision shall not be construed to prohibit more than one arbitrator from presiding over an arbitration: rather, the AAA's rules will govern the number of arbitrators that may preside over an arbitration conducted under this Agreement to Arbitrate.
          <br />
          A party who intends to seek arbitration must first send to the other, by certified mail, written Notice of Dispute ("Notice"). The Notice must include a description of the nature and basis of the claims the party is asserting and the relief sought. The Notice to Nabi Music should be sent to Nabi Music, Attn: Litigation Department, Re: Notice of Dispute, 1609 Clinton Avenue, South Plainfield, New Jersey 07080. Nabi Music will send any Notice to you to the physical address we have on file associated with your Nabi Music account; it is your responsibility to keep your physical address up to date.
          <br />
          If you and Nabi Music are unable to resolve the claims described in the Notice within 30 days after the Notice is sent, you or Nabi Music may initiate arbitration proceedings. A form for initiating arbitration proceedings is available on the AAA's site at www.adr.org. In addition to filing this form with the AAA in accordance with its rules and procedures, the party initiating the arbitration must mail a copy of the completed form to the opposing party. You may send a copy to Nabi Music at the following address: Nabi Music 1609 Clinton Avenue, South Plainfield, New Jersey 07080. In the event Nabi Music initiates an arbitration against you, it will send a copy of the completed form to the physical address we have on file associated with your Nabi Music account. Any settlement offer made by you or Nabi Music shall not be disclosed to the arbitrator.
          <br />
          The arbitration hearing shall be held in the county in which you reside or at another mutually agreed location. If the value of the relief sought is $10,000 or less, you or Nabi Music may elect to have the arbitration conducted by telephone or based solely on written submissions, which election shall be binding on you and Nabi Music subject to the arbitrator's discretion to require an in-person hearing, if the circumstances warrant. In cases where an in-person hearing is held, you and/or Nabi Music may attend by telephone, unless the arbitrator requires otherwise.
          <br />
          The arbitrator will decide the substance of all claims in accordance with applicable law, including recognized principles of equity, and will honor all claims of privilege recognized by law. The arbitrator shall not be bound by rulings in prior arbitrations involving different users, but is bound by rulings in prior arbitrations involving the same Nabi Music user to the extent required by applicable law. The arbitrator's award shall be final and binding and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof.
          <br />
          <br />
          3. Costs of Arbitration. Payment of all filing, administration and arbitrator fees will be governed by the AAA's rules, unless otherwise stated in this Agreement to Arbitrate. If the value of the relief sought is $10,000 or less, at your request, Nabi Music will pay all filing, administration, and arbitrator fees associated with the arbitration. Any request for payment of fees by Nabi Music should be submitted by mail to the AAA along with your Demand for Arbitration and Nabi Music will make arrangements to pay all necessary fees directly to the AAA. In the event the arbitrator determines the claim(s) you assert in the arbitration to be frivolous, you agree to reimburse Nabi Music for all fees associated with the arbitration paid by Nabi Music on your behalf that you otherwise would be obligated to pay under the AAA's rules.
          <br />
          <br />
          4. Severability. With the exception of any of the provisions in Section 1 of this Agreement to Arbitrate ("Prohibition of Class and Representative Actions and Non-Individualized Relief"), if an arbitrator or court decides that any part of this Agreement to Arbitrate is invalid or unenforceable, the other parts of this Agreement to Arbitrate shall still apply. If an arbitrator or court decides that any of the provisions in Section 1 of this Agreement to Arbitrate ("Prohibition of Class and Representative Actions and Non-Individualized Relief") is invalid or unenforceable, then the entirety of this Agreement to Arbitrate shall be null and void. The remainder of the Agreement will continue to apply.
          <br />
          <br />
          5. Opt-Out Procedure. IF YOU ARE A NEW NABI MUSIC USER, YOU CAN CHOOSE TO REJECT THIS AGREEMENT TO ARBITRATE ("OPT-OUT") BY MAILING US A WRITTEN OPT-OUT NOTICE ("OPT-OUT NOTICE"). THE OPT-OUT NOTICE MUST BE POSTMARKED NO LATER THAN 30 DAYS AFTER THE DATE YOU ACCEPT THE USER AGREEMENT FOR THE FIRST TIME. YOU MUST MAIL THE OPT-OUT NOTICE TO  NABI MUSIC, ATTN: LITIGATION DEPARTMENT, RE: OPT-OUT NOTICE, Attn: Litigation Department, Re: Opt Out Notice, 1609 Clinton Avenue, South Plainfield, New Jersey 07080. You must complete the Opt-Out Notice by providing your name, address (including street address, city, state and zip code), and the user ID(s) and email address(es) associated with the Nabi Music account(s) to which the opt-out applies and state that you wish to Opt Out of this Agreement to Arbitrate. You must sign the Opt-Out Notice for it to be effective. This procedure is the only way you can opt out of the Agreement to Arbitrate. If you opt out of the Agreement to Arbitrate, all other parts of the Agreement and this Section will continue to apply to you. Opting out of this Agreement to Arbitrate has no effect on any previous, other, or future arbitration agreements that you may have with us.
          <br />
          <br />
          6. Future Amendments to the Agreement to Arbitrate. Notwithstanding any provision in this Agreement to the contrary, you and we agree that if we make any amendment to this Agreement to Arbitrate (other than an amendment to any notice address or site link provided herein) in the future, that amendment shall not apply to any claim that was filed in a legal proceeding against Nabi Music prior to the effective date of the amendment. The amendment shall apply to all other disputes or claims governed by the Agreement to Arbitrate that have arisen or may arise between you and Nabi Music. We will notify you of amendments to this Agreement to Arbitrate by posting the amended terms on the Website or within our Services at least 30 days before the effective date of the amendments. If you do not agree to these amended terms, you may close your account within the 30 day period and you will not be bound by the amended terms.
        </li>
        <br />
        <li>
          c. Judicial Forum for Legal Disputes.
          <br />
          Unless you and we agree otherwise, in the event that the Agreement to Arbitrate above is found not to apply to you or to a particular claim or dispute, either as a result of your decision to opt out of the Agreement to Arbitrate or as a result of a decision by the arbitrator or a court order, you agree that any claim or dispute that has arisen or may arise between you and Nabi Music must be resolved exclusively by a state or federal court located in Suffolk County, Massachusetts. You and Nabi Music agree to submit to the personal jurisdiction of the courts located within Suffolk County, Massachusetts for the purpose of litigating all such claims or disputes.
        </li>
      </ul>
      <Typography variant="h2">22. Release and Indemnification</Typography>
      IN THE EVENT THAT YOU HAVE A DISPUTE WITH ONE OR MORE MEMBERS OR OTHER USERS OF OUR SERVICES (INCLUDING, WITHOUT LIMITATION, ANY DISPUTE BETWEEN MEMBERS REGARDING ANY TRANSACTION OR USER CONTRIBUTED CONTENT) OR ANY THIRD PARTY WEBSITE THAT MAY BE LINKED TO OR FROM OR OTHERWISE INTERACT WITH OUR SERVICES, INCLUDING WITHOUT LIMITATION ANY SOCIAL MEDIA SITE, YOU HEREBY AGREE TO RELEASE, REMISE AND FOREVER DISCHARGE NABI MUSIC AND OUR RESPECTIVE AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, AND ALL OTHER RELATED PERSONS OR ENTITIES FROM ANY AND ALL MANNER OF RIGHTS, CLAIMS, COMPLAINTS, DEMANDS, CAUSES OF ACTION, PROCEEDINGS, LIABLITIES, OBLIGATIONS, LEGAL FEES, COSTS, AND DISBURSEMENTS OF ANY NATURE WHATSOEVER, WHETHER KNOWN OR UNKNOWN, WHICH NOW OR HEREAFTER ARISE FROM, RELATE TO, OR ARE CONNECTED WITH SUCH DISPUTE AND/OR YOUR USE OF THE WEBSITE AND OUR SERVICES.
      <br />
      <br />
      UNLESS OTHERWISE PROHIBITED BY LAW, YOU WAIVE MASSACHUSETTS CIVIL CODE SECTION 1542, WHICH SAYS: "A GENERAL RELEASE DOES NOT EXTEND TO CLAIMS WHICH THE CREDITOR DOES NOT KNOW OR SUSPECT TO EXIST IN HIS FAVOR AT THE TIME OF EXECUTING THE RELEASE, WHICH, IF KNOWN BY HIM MUST HAVE MATERIALLY AFFECTED HIS SETTLEMENT WITH THE DEBTOR." 
      <br />
      <br />
      YOU HEREBY AGREE TO INDEMNIFY, DEFEND AND HOLD NABI MUSIC  AND OUR RESPECTIVE AGENTS, DIRECTORS, OFFICERS, EMPLOYEES, AND ALL OTHER RELATED PERSONS OR ENTITIES (COLLECTIVELY, THE "INDEMNIFIED PARTIES") HARMLESS FROM AND AGAINST ANY AND ALL LIABILITY AND COSTS INCURRED BY THE INDEMNIFIED PARTIES IN CONNECTION WITH ANY CLAIM ARISING OUT OF YOUR USE OF THE WEBSITE, OUR SERVICESOR OTHERWISE RELATING TO THE BUSINESS WE CONDUCT (INCLUDING, WITHOUT LIMITATION, ANY POTENTIAL OR ACTUAL COMMUNICATION, TRANSACTION OR DISPUTE BETWEEN YOU AND ANY OTHER MEMBER OR THIRD PARTY), ANY CONTENT POSTED BY YOU OR ON YOUR BEHALF OR POSTED BY OTHER USERS OF YOUR ACCOUNT TO THE WEBSITE, ANY USE OF ANY SERVICES OR SERVICE PROVIDED BY A THIRD PARTY PROVIDER, ANY USE OF A TOOL OR SERVICES OFFERED BY US THAT INTERACTS WITH A THIRD PARTY WEBSITE, INCLUDING WITHTOUT LIMITATION ANY SOCIAL MEDIA SITE OR ANY BREACH BY YOU OF THESE TERMS OR THE REPRESENTATIONS, WARRANTIES AND COVENANTS MADE BY YOU HEREIN, INCLUDING WITHOUT LIMITATION, ATTORNEYS' FEES AND COSTS. YOU SHALL COOPERATE AS FULLY AS REASONABLY REQUIRED IN THE DEFENSE OF ANY CLAIM. WE RESERVE THE RIGHT, AT OUR OWN EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU AND YOU SHALL NOT IN ANY EVENT SETTLE ANY MATTER WITHOUT OUR WRITTEN CONSENT. THIS SECTION SURVIVES TERMINATION OF THIS AGREEMENT.
      <Typography variant="h2">23. Commercial Release</Typography>
      By using the Service, you hereby authorize us and our agents, successors and assigns to photograph and/or videotape and/or record you and/or your voice(s) without restriction and to utilize such photographs/videos and/or voice transcriptions or recording for any commercial purpose, including, but not limited to, the promotion and marketing of our Services, without further compensation whatsoever of any kind as a result of such use.
      <Typography variant="h2">24. Taxes</Typography>
      You are responsible for collecting and paying your own taxes due if and when applicable. We are unable to provide you with tax advice and you should consult your own tax advisor.
      <Typography variant="h2">25. Miscellaneous</Typography>
      If either party does not enforce any right or remedy available under this Agreement, that failure is not a waiver of the right or remedy for any other breach or failure by the other party. Our waiver of any requirement in any one instance is not a general waiver of that requirement and does not amend this Agreement. If any part of this Agreement is held invalid or unenforceable, that part is interpreted consistent with applicable laws as nearly as possible to reflect the original intentions of the parties and the rest of this Agreement remains in full force and effect. The provisions of this Agreement that are contemplated to be enforceable after the termination of this Agreement, including, without limitation Sections 4, 8, 11, 21, 22 & 23, shall survive termination of this Agreement. This Agreement, including the documents referenced herein, contains the entire agreement between you and us regarding the use of the Website and/or our Services. This Agreement is binding on the parties hereto and their successors and assigns.
      <br />
      <br />
      Please contact us at <a href="mailto:info@nabimusic.com">info@nabimusic.com</a> with any questions regarding this Agreement.
      <br />
      <br />
      I HAVE READ THIS AGREEMENT AND AGREE TO ALL OF THE PROVISIONS CONTAINED ABOVE.
      <br />
      <br />
      ©2015-2019 Nabi Music Center, LLC. All Rights Reserved.
      <br />
      <br />
      "NabiMusic.com", "NabiMusicCenter.com", "NabiMusic", "Nabi", "NabiMusicCenter", "Nabi Music Center",  "Share the love for music through education" tag line and logo are all trademarks and/or service marks of Nabi Music Center LLC. All other trademarks, service marks, and logos used on the Site are the trademarks, service marks, or logos of their respective owners.
    </div>
  );
};
